[package]
name = "tetris"
version = "0.1.0"
authors = ["Björn Svensson <bjorn.d.svensson@gmail.com>"]
edition = "2018"

[dependencies]
sdl2 = "0.32.2"
rand = "0.3"

[features]
default = ["sdl2/image"]