[package]
name = "threadpool"
version = "0.1.0"
authors = ["Bjorn Svensson <bjorn.d.svensson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
