apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  name: {{ template "simple-http-server.fullname" . }}
  labels:
    app: {{ template "simple-http-server.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "simple-http-server.name" . }}
    release: {{ .Release.Name }}
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
{{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
